### PR TITLE
Add abi parameter to `deploy`

### PR DESCRIPTION
**Pull request by ericglau**
Fixes https://github.com/OpenZeppelin/nile/issues/203

### CODE REVIEW

**Review by andrew-fleming — COMMENTED** [review]
@ericglau excellent addition! I think we just need to update the docs with new param as well

**Comment by ericglau** [comment]
@andrew-fleming The current docs are mostly for the CLI, but this new parameter is only for the NRE's `deploy` function and not exposed in the CLI.  Would it be useful to add this parameter to the CLI as well?

**Comment by andrew-fleming** [comment]
Great question. Maybe we should include it in the CLI just for consistency with documenting the param? Otherwise, I think it'll be difficult for users to know about this feature. What do you think?

**Comment by martriay** [comment]
+1 to add it to the CLI

**Comment by ericglau** [comment]
Added the param to cli and docs.

**Review by andrew-fleming — APPROVED** [review]
Looks good to me!

**Pull request merged**
