### PR TITLE
Fix: typos

### PR DESCRIPTION
**Pull request by omahs**
Fix: typos

### CODE REVIEW

**Review by ericnordelo — APPROVED** [review]
Looking good. Thanks @omahs for taking the time!

**Review by martriay — APPROVED** [review]
thanks!

**Review by martriay — CHANGES_REQUESTED** [review]
oops, there seem to be some conflicts. could you make sure to run the linter?

**Comment by omahs** [comment]
@martriay it should be good now :)

**Review by ericnordelo — APPROVED** [review]
LGTM!

**Review by martriay — APPROVED** [review]

**Pull request merged**
