### PR TITLE
Update account artifacts from cairo-contracts

### PR DESCRIPTION
**Pull request by ericnordelo**
This is an update of the artifacts from the last version of Account.cairo preset in cairo-contracts.

With this last update, transactions can be simulated and gas fees estimated allowing the QUERY_VERSION number for the transaction version in the account.

### CODE REVIEW

**Comment by ericnordelo** [comment]
The update comes from [this PR](https://github.com/OpenZeppelin/cairo-contracts/pull/486) in cairo-contracts.

**Review by andrew-fleming — DISMISSED** [review]
👍

**Review by martriay — DISMISSED** [review]

**Comment by martriay** [comment]
I'm getting different hashes between https://github.com/OpenZeppelin/cairo-contracts/pull/486's latest and this.

486's:
```
(env) ➜  cairo-contracts git:(feat/allow-query-calls-#471) shasum -a 256 artifacts/Account.json 
076d902c6a7f80b69d4cb6de95c9e9e6926b29241fab4fb70942011c1109260e  artifacts/Account.json
(env) ➜  cairo-contracts git:(feat/allow-query-calls-#471) git hash-object artifacts/Account.json 
496deecfabe6d96079b206a2187c5dc3cf07c893
```

this PR:
```
(env) ➜  nile git:(feat/update-account-artifacts-c#471) shasum -a 256 src/nile/artifacts/Account.json 
1900a3cb45074b80bf488a778f779c33b3808acbb3d39e880fa3d1a724678e48  src/nile/artifacts/Account.json
(env) ➜  nile git:(feat/update-account-artifacts-c#471) git hash-object src/nile/artifacts/Account.json 
3b4c6ffaa80637bc2a529300f7f0998f78f7d1ad
```

**Comment by martriay** [comment]
hmm this is why. I wonder how can we make this easily reproducible and cross-checkable
image

**Review by martriay — APPROVED** [review]

**Pull request merged**
