### PR TITLE
add --seed option to nile node command

### LINKED ISSUE #148: Cannot replicate `starknet-devnet` account sequence through `nile node`
`startknet-devnet` accepts a `--seed` that allows for deterministic prefunded account sequences. It could be nice to be able to use that feature through `nile node` - currently you cannot.

I overstepped and opened a PR that adds a `--seed` option to `nile node`: https://github.com/OpenZeppelin/nile/pull/147 

My motivation for wanting this feature was to make the dev process for writing front ends a bit easier. The idea being that I would know the deployed & prefunded accounts, and could use them for testing things out on a local network. Turns out neither Argent nor Bravos lets me import accounts, so not sure this would end up helping me out. But figured I'd keep it open.

### PR DESCRIPTION
**Pull request by kevinhalliday**
Fixes #148. Adding the `--seed` options to `nile node` allows callers to get deterministic pre-funded accounts

Found myself wanting this feature so thought I would propose in the form of a PR. If this is something you might consider I could work on tests for it. If not, no hard feelings.

### CODE REVIEW

**Comment by kevinhalliday** [comment]
> Hi @kevinhalliday thanks for the interest in contributing, normally when opening a PR we prefer if an issue is open beforehand to check with the community and ourselves and discuss possible options to solve or work on the issue, in this case it's our fault since we don't yet have a CONTRIBUTING file on this repo (pending issue #21).
> 
> So, could you please open an issue where you describe why would it be beneficial, etc. And then link it to this PR?

yep, apologies!

**Review by martriay — CHANGES_REQUESTED** [review]
Hello @kevinhalliday, thanks for doing this! It looks good, so i'd suggest you continue with the tests, since docs are covered already :)

**Comment by kevinhalliday** [comment]
@martriay thanks! added some tests. put my motivation in the commit message. tried not to introduce any new patterns

**Comment by andrew-fleming** [comment]
Hey @kevinhalliday, sorry for the delay. Do you mind if I push a commit to fix conflicts?

**Comment by kevinhalliday** [comment]
> Hey @kevinhalliday, sorry for the delay. Do you mind if I push a commit to fix conflicts?

I do not mind!

**Review by martriay — APPROVED** [review]
This looks very good! Nice addition.

**Pull request merged**
