### PR TITLE
Add tests for "compile" and "clean" CLI commands

### PR DESCRIPTION
**Pull request by TimNooren**
See https://github.com/OpenZeppelin/nile/issues/13

- Extracts `clean` command implementation to make it easier to test.
- Contract compilation itself is not tested.

Looks like I cannot assign reviewers, but as this is not time critical I'm just leaving it here for now:)

### CODE REVIEW

**Comment by martriay** [comment]
Thanks for this very much needed PR! I hope it's the kickoff of a comprehensive test suite :)

How would you suggest we test compilation itself?

**Comment by fracek** [comment]
I was thinking one way to test that is to have end to end tests in the CI. Basically have a shell where it runs all nile commands like a user would.

**Comment by TimNooren** [comment]
Some end-to-end tests sounds like a good approach👍  Happy to give that a go (in a separate PR?). Could be done with `pytest` as well, since `click` has quite nice testing support.

**Comment by fracek** [comment]
I too think end to end tests should be a separate PR. I will open an issue to track that.

**Comment by martriay** [comment]
Agree with all your comments, let's continue that chat on the other issue. Really good work on this PR!

Could you add some testing instructions to the README? :)

**Comment by TimNooren** [comment]
> Could you add some testing instructions to the README? :)

Added a bit more information. Let me know what you think:)

**Comment by TimNooren** [comment]
Fixed the failing tests (I think). Missed one case where `starknet-compile` was being called.

**Comment by martriay** [comment]
Thanks! 🎉

**Pull request merged**
