### PR TITLE
feat: --port option for node command

### LINKED ISSUE #35: Can't run nile node in macOS
Hi, 

I'm on macOS Big Sur, and there is some system process running at port 5000. Cause of which, `nile node` fails to run. 

Is there a way to specify the port in `nile node` ?

### PR DESCRIPTION
**Pull request by milancermak**
Resolves #35.

I had a couple of minutes of time on my hands and the issues seems stale so I figured I'll fix it. Let me know if I missed something (those minutes were accompanied by a pilsner 🍺  :))

### CODE REVIEW

**Comment by martriay** [comment]
Thanks for doing this, but I don't think https://github.com/OpenZeppelin/nile/pull/46 is stale 😬, which btw includes testing 🙏

**Comment by milancermak** [comment]
Whoopsie :) Should I close this one?

**Comment by martriay** [comment]
Probably, sorry.

**Comment by milancermak** [comment]
No problem

**Pull request closed without merging**
