### PR TITLE
Add host and port options for "node" command

### PR DESCRIPTION
**Pull request by ftupas**
Hi there,

Kindly see #35. I've added an option to customize the host and node port when running `nile node` and an end-to-end test in `test_main.py`

Running the command `nile node --host localhost --port 5001` should yield something like this

image

Please let me know if this looks alright and any feedback is welcome, thanks! 🙂

### CODE REVIEW

**Comment by fracek** [comment]
Looks good so far! Can you check why the tests are failing?

**Comment by ftupas** [comment]
Thanks for the review, will look into it!

**Comment by ftupas** [comment]
I've found the error,

**Comment by ftupas** [comment]
It seems that the same error is thrown on `python 3.10`  like the end-to-end `test_compile` so I've added the same mark for failing.

image

This only covers the options for `node` command though. I realized I need more time to cover `deploy`, `call/invoke` but if this PR can be merged, then I'll try to solve them in a separate one if that's better. Please let me know 🙂 thank you!

**Comment by ftupas** [comment]
Since [GATEWAY](https://github.com/OpenZeppelin/nile/blob/main/src/nile/common.py#L11) variable was static, `**deploy/call/invoke etc.**` commands wouldn't target the correct `gateway_url` if custom host or port was used so I've created a `node.json` file with default values `{"localhost": "http://localhost:5000/"}`. It gets overwritten with respective host and port whenever `nile deploy` is executed so the succeeding commands will work properly 🙂 Please let me know if this is okay, thank you!

**Review by fracek — APPROVED** [review]
Looks good to me. Thank you for the changes.

**Comment by ftupas** [comment]
Happy to contribute, thanks for the review and approval 🙂

**Pull request merged**
